[build]
  command = "npm run build"   
  publish = "dist"            

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
